require('dotenv').config();
const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const bodyParser = require('body-parser');
const app = express();
app.use(cors()); app.use(bodyParser.json());
const PORT = process.env.PORT || 4000;
mongoose.connect(process.env.MONGO_URI, {useNewUrlParser:true, useUnifiedTopology:true}).then(()=>{console.log('Mongo connected');}).catch(err=>{console.error(err)});
app.get('/', (req,res)=>res.send('Visitor Auth Backend'));
app.listen(PORT, ()=> console.log('Server running on', PORT));
